### ISSUE TITLE
How do I exactly install luna-kit?

### ISSUE THREAD

**Issue by Futatabi6** [ego-lay-atman-bay/luna-kit#1]
For a start, i apologize for being so dumb at this. I really don't know how to use codes and stuff. the instalation guide says to make sure python and git are installed, and I'm sure they are since i installed both of them and i also restarted my pc to avoid problems. And then it says to run a code. Where do I exactly run the code? I tried running it on cmd, on python and even in git. But both Cmd and Git doesn't recognize the code, and python just gives me a straight error. So I really don't know what to do. Again, I'm really sorry for this. 
![error](https://github.com/user-attachments/assets/23cfdb98-5c1d-4de8-8bff-8dd0d55978d4)

**Comment by ego-lay-atman-bay** [comment]
Don't worry, I have a feeling I know what's wrong, and how to fix it.

cmd is indeed the right place to run the commands.

I have a feeling the reason why it didn't work, was because pip wasn't on the PATH. Try running this instead.

```
py -m pip install git+https://github.com/ego-lay-atman-bay/luna-kit/
```

If you want to fix the issue with pip, and not have to use `py -m`, here's how to do it.

1. Find the python installation folder. It should be something like `C:\Python313` or `C:\Users\USER\AppData\Local\Programs\Python\Python313`. There should be a folder called `Scripts` there.
2. Open the windows search, and search for "Edit environment variables"
3. In the new dialog, click on "Environment variables".
4. There should be 2 lists of varoables, user variables and system variables.
5. If you installed python for just your user, find the PATH variable in the user variables, and if you installed it for everyone, find the PATH variable in the system variables. Double click it.
6. In the new dialog, just click "new", then paste in the path to you python installation folder, and add `\Scripts` to the end. For example, `C:\Python313\Scripts` or `C:\Users\USER\AppData\Local\Programs\Python\Python38\Scripts`.
7. Click ok on all the dialogs.
8. Now open a new cmd window, and run `pip --version` to check if it works.

**Comment by Futatabi6** [comment]
Thank you so much for your dedication and help!!! It worked! Now i'm trying to extract the ark files. this is how i'm doing it:
**luna-kit ark H:\Programas\MMD\Addons\Ripping Stuff\My Little Pony Magic Princess\files000_and_mlpextra2_astc_veryhigh.ark -o H:\Programas\MMD\Addons\Ripping Stuff\My Little Pony Magic Princess\files\extracted**

and its giving me this error:
**usage: luna-kit [-h] {ark,atlas,loc,sheet,xml} ...
luna-kit: error: unrecognized arguments: Stuff\My Little Pony Magic Princess\files\extracted**
Can you tell me what did i do wrong? Sorry if this isn't the right place to ask for help!!

**Comment by ego-lay-atman-bay** [comment]
You have to put quotes around the folder paths (if they have spaces on them). I also suggest doing

```
luna-kit ark "H:\Programas\MMD\Addons\Ripping Stuff\My Little Pony Magic Princess\files\*.ark" -o "H:\Programas\MMD\Addons\Ripping Stuff\My Little Pony Magic Princess\files\extracted"
```
So you can extract all the ark files at once.

**Comment by Futatabi6** [comment]
Thank you so much!!! I even figured it out myself xD I have to pay more attention. Thanks a lot for your help and dedication on the code!! You have noooo idea how i dreamed about this game being finally rippeable. Thanks  alot!! I'll avoid asking dumb questions. ty ty ❤

**Comment by ego-lay-atman-bay** [comment]
You're welcome. Also, these are valid questions that many new users (to the command line) run into. I'm just willing to help out any way I can.
